import { DataTable } from "../components/DataTable";
import type { DashboardSnapshot } from "../types/dashboard";
import { formatCurrency } from "../utils/format";

type PositionsProps = {
  snapshot: DashboardSnapshot | null;
};

export function Positions({ snapshot }: PositionsProps) {
  const positions = snapshot?.positions ?? [];

  return (
    <section className="panel page-panel">
      <div className="panel-header">
        <h3>Simulated Exposure</h3>
        <p>Inventory and PnL state generated by the local execution simulator on top of real market data.</p>
      </div>
      <DataTable
        columns={["Symbol", "Status", "Quantity", "Avg Price", "Market Value", "Unrealized PnL"]}
        rows={positions.map((position, index) => [
          position.symbol ?? `Asset ${index + 1}`,
          position.status,
          position.quantity.toFixed(2),
          formatCurrency(position.average_price),
          formatCurrency(position.market_value),
          formatCurrency(position.unrealized_pnl),
        ])}
      />
    </section>
  );
}
